"""Regenerate src/keywords.ts from SQLFluff's Spark SQL and Databricks keyword lists.

The checker only needs to know which words *might* be keywords: a word in the
set is never treated as a bare identifier by the missing-comma heuristics, so
an over-full set costs a little recall and never a false positive. That is why
reserved and unreserved lists are merged, and why EXTRA adds words the
grammar gives meaning to that the lists do not carry.

Usage:
    python scripts/gen_keywords.py ../sqlfluff
"""
from __future__ import annotations

import pathlib
import sys

EXTRA = {
    # Interval units, singular and plural: `INTERVAL 3 HOURS`.
    "YEARS", "MONTHS", "WEEK", "WEEKS", "DAYS", "HOURS", "MINUTES", "SECONDS",
    "MILLISECOND", "MILLISECONDS", "MICROSECOND", "MICROSECONDS",
    "NANOSECOND", "NANOSECONDS", "QUARTER", "DAYOFWEEK", "DAYOFYEAR",
    # Expression continuations that must never read as an alias.
    "FILTER", "OVER", "WITHIN", "IGNORE", "RESPECT", "NULLS", "COLLATE",
    "ESCAPE", "DIV", "RLIKE", "REGEXP", "ILIKE", "LIKE", "IS", "NOT", "IN",
    "BETWEEN", "AND", "OR", "EXISTS", "ANY", "SOME", "ALL", "INTERVAL", "TO",
    "AT", "ZONE", "DISTINCT", "SEMI", "ANTI", "STREAM", "LIVE", "VARIANT",
    "TIMESTAMP_NTZ", "TIMESTAMP_LTZ", "IDENTIFIER", "RECURSIVE", "EXCEPT",
    "REPLACE", "LATERAL", "PIVOT", "UNPIVOT", "QUALIFY", "MINUS", "WATERMARK",
    "DELAY", "CLONE", "SHALLOW", "DEEP", "VERSION", "OF",
    # Upper-case words in the `syntax:` blocks that databricks-sql-corpus
    # transcribed from the Databricks SQL reference (corpus/reference/*.yml,
    # read 2026-09-25) and that the SQLFluff lists lack. Left out on purpose:
    # common column names (ID, NAME, VALUE, MAX, URL, LEVEL, MODEL, OWNER,
    # FILE, METADATA), GET DIAGNOSTICS item names (MESSAGE_TEXT, ROW_COUNT,
    # ...), hint names (BROADCAST, REPARTITION, ...) and function names.
    "ALWAYS", "ANONYMOUS", "APPLY", "ASENSITIVE", "ASYNC", "ATOMIC", "BEGIN", "BITEMPORAL",
    "BLOOMFILTER", "CALL", "CATALOGS", "CHECKPOINT", "CLEAN", "COLLATION", "CONDITION",
    "CONNECTION", "CONNECTIONS", "CONTAINS", "CONTINUE", "CONVERT", "COPY", "COPY_OPTIONS",
    "CREDENTIAL", "CREDENTIALS", "CURSOR", "DEC", "DECLARE", "DEFAULT", "DEFINE", "DEFINER",
    "DENY", "DETERMINISTIC", "DIAGNOSTICS", "DISABLE", "DO", "DROPPED", "EFFECTIVE", "ELSEIF",
    "EMPTY", "ENABLE", "ENCRYPTION", "ENVIRONMENT", "EVERY", "EXCLUDE", "EXECUTE", "EXIT",
    "FILES", "FORCE", "FORMAT_OPTIONS", "FOUND", "FSCK", "GENERATED", "GET", "GRANTS", "GROUPS",
    "HANDLER", "IDENTITY", "IMMEDIATE", "INCLUDE", "INCREMENT", "INHERIT", "INOUT", "INSENSITIVE",
    "INVENTORY", "INVOKER", "ITERATE", "LANGUAGE", "LEAVE", "LITE", "LOCATIONS", "LOOP", "MATCH",
    "MATCHES", "MATCH_RECOGNIZE", "MATERIALIZED", "MEASURES", "METASTORE", "MODIFIED", "MODIFIES",
    "NEAREST", "NOSCAN", "OFFSET", "ONE", "PAST", "PATTERN", "PER", "PERCENT", "POLICIES", "POLICY",
    "PRIVILEGES", "PROCEDURE", "PROCEDURES", "PROVIDERS", "READ", "READS", "RECIPIENTS",
    "RECURSION", "REORG", "REPEAT", "RESIGNAL", "RESOLVE", "RESTORE", "RETURN", "RETURNS", "ROOM",
    "SCHEMAS", "SECURITY", "SEQUENCE", "SERVICE", "SHARE", "SHARES", "SIGNAL", "SINGLE", "SKIP",
    "SQLEXCEPTION", "SQLSTATE", "STORAGE", "TIMESTAMP", "UNDROP", "UNIFORM", "UNTIL", "UPGRADE",
    "USERS", "VACUUM", "VALIDATE", "VERIFY", "WHILE", "WITHOUT",
    # Other clause words from the reference: row-pattern matching, FETCH,
    # pipelines, pipe syntax, time travel.
    "SUBSET", "PERMUTE", "RUNNING", "FINAL", "CLASSIFIER", "MATCH_NUMBER", "PREV", "FETCH",
    "ONLY", "TIES", "AUTO", "NONE", "CDC", "SCD", "KEYS", "STORED", "TRACK", "HISTORY", "ONCE",
    "SCHEDULE", "CRON", "TRIGGER", "INCREMENTAL", "FLOW", "EXPECT", "VIOLATION", "FAIL", "DETAIL",
    "EXTENDED", "AGGREGATE", "EXTEND", "RENAME", "RETAIN", "DRY", "RUN", "SYNC", "STREAMING",
    "TEMPORARY", "VAR", "VARIABLE", "EVOLUTION", "TYPE",
}


def _load(path: pathlib.Path) -> set[str]:
    scope: dict[str, object] = {}
    exec(compile(path.read_text(), str(path), "exec"), scope)
    words: set[str] = set()
    for name in ("RESERVED_KEYWORDS", "UNRESERVED_KEYWORDS"):
        values = scope.get(name, [])
        assert isinstance(values, list), f"{path}: {name} is not a list"
        words.update(str(w).upper() for w in values)
    return words


def main(sqlfluff_root: str) -> None:
    dialects = pathlib.Path(sqlfluff_root) / "src" / "sqlfluff" / "dialects"
    words = (
        _load(dialects / "dialect_sparksql_keywords.py")
        | _load(dialects / "dialect_databricks_keywords.py")
        | EXTRA
    )
    body = "\n".join(f'  "{w}",' for w in sorted(words))
    out = pathlib.Path(__file__).resolve().parents[1] / "src" / "keywords.ts"
    out.write_text(
        "// Generated by scripts/gen_keywords.py -- do not edit by hand.\n"
        "//\n"
        "// Source: SQLFluff's sparksql and databricks keyword lists (MIT,\n"
        "// https://github.com/sqlfluff/sqlfluff), plus the EXTRA words in the\n"
        "// generator. Reserved and unreserved are merged on purpose: see the\n"
        "// generator's docstring.\n"
        "\n"
        "export const KEYWORDS: ReadonlySet<string> = new Set([\n"
        f"{body}\n"
        "]);\n"
    )
    print(f"wrote {len(words)} keywords to {out}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "../sqlfluff")
